# Change these first
owner: kristiankunc # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: VatNotif web
    url: https://vatnotif.kristn.co.uk
  - name: VatNotif API
    url: https://vatnotif-api.kristn.co.uk
  - name: Ratar TD game
    url: https://td-game.kristn.co.uk
  - name: Ratar TD web
    url: https://td.kristn.co.uk

status-website:
  cname: status.kristn.co.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
